# Generated by Django 5.2.3 on 2025-07-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vehicle_created_by_alter_vehicle_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_img',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_image'),
        ),
    ]
