# Generated by Django 5.2.3 on 2025-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
